### ISSUE TITLE
Search string for one hour precip fails. Lots of corner cases

### ISSUE THREAD

**Issue by scollis** [blaylockbk/Herbie#156]
In order to get the 1 hour precip from HRRR you need to brute force.
See this notebook.
https://github.com/scollis/notebooks/blob/master/Herbie_Chicago_precip.ipynb

Need to update the examples to include this brute force method and show an example with Fast Herbie.

I may have time to get to this during this week.

**Comment by blaylockbk** [comment]
Thanks for pointing this out. Yeah, I wish you could just use `searchString="ACPC:surface"` to get both hourly and total precip, but cfgrib has a limitation reading both from a grib file (https://github.com/ecmwf/cfgrib/issues/187).

I found what the problem is here...that regex searchString won't match these because of the zero:
```
:APCP:surface:10-11 hour acc fcst
:APCP:surface:20-21 hour acc fcst
:APCP:surface:30-31 hour acc fcst
:APCP:surface:40-41 hour acc fcst
```

(I never tried requesting precip data at that long lead time, so I'm glad you found this). I'll figure out what the right regex should be; the docs need to be updated.

**Comment by scollis** [comment]
Or we can use my brute force technique. It is an example of how to construct a query which has complex rules. 

```qstr = '(' 
nfcst = 47
for i in range(nfcst):
    if i != nfcst -1:
        qstr = qstr +  f':APCP:surface:{i}-{i+1} h*|'
    else:
        qstr = qstr +  f':APCP:surface:{i}-{i+1} h*)'

```

**Comment by blaylockbk** [comment]
Using 
```python
searchString=":APCP:surface:[1-9].*-[1-9].*"
```
(with `.*` instead of `*`) *almost* does the trick.

**Old Search String doesn't capture all cases**
<img width="377" alt="image" src="https://user-images.githubusercontent.com/6249613/212709742-0e2a4b41-62bd-45f4-bcf3-fcdfa7a31b5d.png">

**New Search String _almost_ captures everything**
<img width="536" alt="image" src="https://user-images.githubusercontent.com/6249613/212711057-e41e7cf6-c4c8-45bf-84f3-6008b60030d2.png">

**Comment by blaylockbk** [comment]
(If ChatGTP was online, I'd ask it to figure out the right search string) 😂

**Comment by blaylockbk** [comment]
The brute force method is a good example I'll add to the docs for complex cases.

There's probably a cleaner regex for this, but this captures all 1-hr accumulated precip
```
:APCP:surface:(?:0-1|[1-9].*-\d+) hour acc fcst
```
<img width="418" alt="image" src="https://user-images.githubusercontent.com/6249613/212716691-558f42a7-8b25-4bab-ba2f-74c928c9149f.png">
