### ISSUE TITLE
Filename Too Long

### ISSUE THREAD

**Issue by danieldjewell** [blaylockbk/Herbie#24]
When subsetting from a full GRIB2 with lots of fields, the code at: 

https://github.com/blaylockbk/Herbie/blob/0beffe1426be8f12bd3c931650db29be7e04cff3/herbie/archive.py#L395-L400

attempts to create a filename that's too long and fails. 

An example would be:
```python

h = Herbie('2021-09-22 12:00', model='gfs')
#download full GRIB2 for the GFS @ f000
h.download()
ds = h.xarray('HGT')
#so many field numbers match that Herbie fails with an OSError filename too long
```

### Fix Ideas
I have a couple of thoughts:

1. Could hash the list of field numbers (something quick and short, `sha1` maybe?) and use that as the filename. That would allow for future access to the same set of GRIB fields (by hashing the same list)... but would make it impossible to figure out what's in the subsetted file just from the filename.
2. Write a herbie index file that defines "these fields are in filename X" and use a shorter filename.
3. Write each GRIB2 record to its own file (although this would create a large number of files potentially, there's basically zero overhead otherwise, since GRIB2 files are just concatenated records...) This actually could be useful as the granularity would allow for easy selection. (And also possibly solve another issue that I'm investigating -- if you've downloaded the full GRIB2 as above and then run the `.xarray('HGT')` command as above, it *appears* that Herbie won't subset the file that was already downloaded ... but will instead *redownload* the requested subset. In other words, instead of opening the full GRIB2 that was already downloadrd and grabbing all of the "HGT" records, it'll redownload the GRIB2 "HGT" records...)
4. Use a tempfile ?

**Comment by blaylockbk** [comment]
Thanks for raising this issue. It's not one I have run into before. When I execute that block of code on my Linux I don't get a "filename too long error" (are you on windows?). Still, this needs to be fixed.

I do like your idea in 1. It was easy to implement and I pushed the changes. Herbie will now save file subsets with a hash label in the file name. I'm not too worried about the filename hash not being descriptive of the file contents because the user will likely know what they are subsetting and they can always use the `wgrib2` or `grib_ls` tools to print the contents of the grib file.

In comment 3, you mention 

> if you've downloaded the full GRIB2 as above and then run the .xarray('HGT') command as above, it appears that Herbie won't subset the file that was already downloaded ... but will instead redownload the requested subset.

I have noticed this (I created Issue #25). I'll have to investigate this someday--Herbie should check for a local file first and subset that if it exists. If it does what I think it does, the printed statement is wrong and needs to be fixed. Or maybe it's not doing what I think it does. But I think it is using the remote copy of the .idx file and using that to cURL the local copy. Again, I'll look into it and double check that is what it is actually doing.
