### ISSUE TITLE
Herbie can't find index file for GFS grib2 files

### ISSUE THREAD

**Issue by sramirez** [blaylockbk/Herbie#42]
Seems there exist some problems when finding indexes even it they exist from version>=0.0.7
Even if I replace the suffix, it raises an error: "No index found for..."

H = Herbie(date, priority='aws', product='pgrb2.0p25', model='gfs', fxx=fxx, IDX_SUFFIX='.idx')
H.download() <- error

**Comment by blaylockbk** [comment]
Thanks @sramirez for finding and reporting this issue 👍🏼 

This bug was introduced in `Herbie 0.0.8` when I implemented a new method for specifying the suffix of the index files.

The bug is caused when Herbie replaces the suffix of the GRIB file with the index suffix, **but that doesn't work when the GRIB file doesn't have a suffix!** (e.g., `gfs.t00z.goessimpgrb2.0p25.f006` doesn't end in `.grib2`).

I made a change in the master branch to only replace the suffix if the file ends in any of `['.grb', '.grib', '.grb2', '.grib2']`.
